version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres-tool
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-sensordb}
      POSTGRES_USER: ${DB_USER:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-app}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

